# based on https://blog.jessfraz.com/post/building-container-images-securely-on-kubernetes/
apiVersion: v1
kind: Pod
metadata:
  name: img
  labels:
    run: img
  annotations:
    container.apparmor.security.beta.kubernetes.io/img: unconfined
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: img
    image: r.j3ss.co/img:v0.5.7
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    securityContext:
      procMount: Unmasked
    volumeMounts:
    - name: cache-volume
      mountPath: /tmp
    - name: google-cloud-key
      mountPath: /var/secrets/google
    env:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /var/secrets/google/key.json
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: google-cloud-key
    secret:
      secretName: img-secret
  restartPolicy: Never
  