# based on https://blog.jessfraz.com/post/building-container-images-securely-on-kubernetes/
apiVersion: v1
kind: Pod
metadata:
  name: img
  labels:
    run: img
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: img
    image: r.j3ss.co/img:v0.5.7
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    securityContext:
      procMount: Unmasked
      privileged: true
    volumeMounts:
    - name: cache-volume
      mountPath: /tmp
  volumes:
  - name: cache-volume
    emptyDir: {}
  restartPolicy: Never
  