# based on https://blog.jessfraz.com/post/building-container-images-securely-on-kubernetes/
apiVersion: v1
kind: Pod
metadata:
  name: img
  labels:
    run: img
  annotations:
    container.apparmor.security.beta.kubernetes.io/img: unconfined
    container.seccomp.security.alpha.kubernetes.io/img: unconfined
spec:
  securityContext:
    runAsUser: 1000
  serviceAccountName: img
  containers:
  - name: img
    image: gcr.io/melgin/gcloud-img:0.1.1
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    # securityContext:
    #   procMount: Unmasked
    volumeMounts:
    - name: docker-config
      mountPath: /.docker/
    - name: gcloud-config
      mountPath: /.config/gcloud
    - name: cache-volume
      mountPath: /tmp/
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: docker-config
    emptyDir: {}
  - name: gcloud-config
    emptyDir: {}
  - name: cache-volume
    emptyDir: {}
  restartPolicy: Never
  