---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: img-gcr@melgin.iam.gserviceaccount.com
  name: img

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: img
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - img
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","get","list","patch","update","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: img
  namespace: img
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: img
subjects:
- kind: ServiceAccount
  name: img